from typing import Dict, Any
from loguru import logger
from app.core.config import settings


def format_github_comment(state: Dict[str, Any]) -> str:
    """Format the review as a beautiful GitHub PR comment."""
    score = state.get("overall_score", 0)
    verdict = state.get("verdict", "Approve with suggestions")
    summary = state.get("summary", "")
    issues = state.get("issues", [])
    security_issues = state.get("security_issues", [])
    performance_issues = state.get("performance_issues", [])
    suggestions = state.get("suggestions", [])
    positive_aspects = state.get("positive_aspects", [])
    must_fix = state.get("must_fix_before_merge", [])
    similar_issues = state.get("similar_issues", [])

    # Score emoji
    if score >= 8:
        score_emoji = "🟢"
    elif score >= 6:
        score_emoji = "🟡"
    elif score >= 4:
        score_emoji = "🟠"
    else:
        score_emoji = "🔴"

    verdict_emoji = {
        "Approve": "✅",
        "Approve with suggestions": "✅",
        "Request changes": "⚠️",
        "Block": "🚫",
    }.get(verdict, "📋")

    comment = f"""## 🤖 AI Code Review — JobLens Code Reviewer

{score_emoji} **Score: {score:.1f}/10** &nbsp;&nbsp; {verdict_emoji} **{verdict}**

---

### 📋 Summary
{summary}

"""

    # Must fix
    if must_fix:
        comment += "### 🚫 Must Fix Before Merge\n"
        for item in must_fix[:3]:
            comment += f"- ❌ {item}\n"
        comment += "\n"

    # Security issues
    if security_issues:
        comment += f"### 🔒 Security Issues ({len(security_issues)})\n"
        for issue in security_issues[:5]:
            sev = issue.get("severity", "medium").upper()
            comment += f"- **[{sev}]** `{issue.get('file', '')}` — {issue.get('message', '')}\n"
            comment += f"  > 💡 {issue.get('suggestion', '')}\n"
        comment += "\n"

    # Code quality issues
    if issues:
        comment += f"### ⚠️ Code Quality Issues ({len(issues)})\n"
        for issue in issues[:6]:
            sev = issue.get("severity", "low").upper()
            line = f"line {issue['line']}" if issue.get("line") else ""
            comment += f"- **[{sev}]** `{issue.get('file', '')}` {line} — {issue.get('message', '')}\n"
            comment += f"  > 💡 {issue.get('suggestion', '')}\n"
        comment += "\n"

    # Performance
    if performance_issues:
        comment += f"### ⚡ Performance Issues ({len(performance_issues)})\n"
        for issue in performance_issues[:3]:
            comment += f"- `{issue.get('file', '')}` — {issue.get('message', '')}\n"
            comment += f"  > 💡 {issue.get('suggestion', '')}\n"
        comment += "\n"

    # Suggestions
    if suggestions:
        comment += "### 💡 Suggestions\n"
        for s in suggestions[:5]:
            comment += f"- {s}\n"
        comment += "\n"

    # Positive aspects
    if positive_aspects:
        comment += "### ✅ What's Good\n"
        for p in positive_aspects[:3]:
            comment += f"- {p}\n"
        comment += "\n"

    # Similar past issues (RAG)
    if similar_issues:
        comment += "### 🔍 Similar Past Issues (Semantic Search)\n"
        for si in similar_issues[:2]:
            score_val = si.get("similarity_score", 0)
            comment += f"- {si.get('message', '')} *(similarity: {score_val:.0%})*\n"
        comment += "\n"

    comment += """---
<sub>🤖 Generated by **AI Code Reviewer** · Powered by LangGraph + CodeBERT + OpenRouter · [Dashboard](https://ai-code-reviewer.onrender.com)</sub>"""

    return comment


def run_reporter_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Reporter Agent — Third and final agent in LangGraph pipeline.
    Responsibilities:
    - Format review as GitHub comment
    - Post comment to GitHub PR
    - Store code issues in FAISS for future RAG retrieval
    - Return final state
    """
    logger.info("Reporter agent starting...")

    # Format comment
    comment = format_github_comment(state)
    state["github_comment"] = comment

    # Post to GitHub if token and PR info available
    posted = False
    repo_name = state.get("repo_name", "")
    pr_number = state.get("pr_number")

    if settings.GITHUB_TOKEN and repo_name and pr_number:
        try:
            from github import Github
            g = Github(settings.GITHUB_TOKEN)
            repo = g.get_repo(repo_name)
            pr = repo.get_pull(int(pr_number))
            pr.create_issue_comment(comment)
            posted = True
            logger.info(f"Posted review to GitHub PR #{pr_number}")
        except Exception as e:
            logger.error(f"Failed to post to GitHub: {e}")

    state["posted_to_github"] = 1 if posted else 0

    # Store issues in FAISS for future RAG retrieval
    try:
        from app.services.embeddings.code_embedder import get_faiss_store
        faiss_store = get_faiss_store()
        all_issues = (
            state.get("issues", []) +
            state.get("security_issues", []) +
            state.get("performance_issues", [])
        )
        diff_text = state.get("diff_text", "")[:500]
        for issue in all_issues[:5]:
            faiss_store.add_code_snippet(
                diff_text,
                {
                    "repo": repo_name,
                    "pr_number": pr_number,
                    "severity": issue.get("severity", "low"),
                    "type": issue.get("type", "unknown"),
                    "message": issue.get("message", ""),
                    "suggestion": issue.get("suggestion", ""),
                }
            )
        logger.info(f"Stored {len(all_issues)} issues in FAISS")
    except Exception as e:
        logger.warning(f"FAISS storage failed: {e}")

    state["status"] = "completed"
    logger.info(f"Reporter done. Posted to GitHub: {posted}")
    return state
